### ISSUE TITLE
Font not rendering.

### ISSUE THREAD

**Issue by Ivan-Khar** [alphaqu/DashLoader-Legacy#4]
Minecraft rendering any letter as cubes.
What I should see: **[Link](https://imgur.com/Ft50KVt)**
What I get: **[Link](https://imgur.com/WUu6nVW)**

With Force Unicode Font everything works fine.
And when I trying to turn Force Unicode Font and change it to another language the game just crashing.

Crash report and mod list: [crash-2021-04-16_20.15.17-client.txt](https://github.com/alphaqu/DashLoader/files/6326853/crash-2021-04-16_20.15.17-client.txt)

**Comment by Ivan-Khar** [comment]
Additional log: [latest.log](https://github.com/alphaqu/DashLoader/files/6326979/latest.log)

**Comment by Ivan-Khar** [comment]
This was due to the resource pack that changes the font.

**Comment by alphaqu** [comment]
Reopened to tag resourcepack custom fonts

**Comment by Blobanium** [comment]
Similar issue here, but the text looks way to messed up (also this is when trying to force unicode font)

![Capture](https://user-images.githubusercontent.com/45613796/115475707-14071500-a1f5-11eb-86e1-b61d8553c988.PNG)

**Comment by alphaqu** [comment]
Should be fixed with 1.2-alpha

**Comment by justinmok** [comment]
Still having this issue on 1.5. Mod complained I didn't have the `minecraft:negative_space.ttf` font installed, so I installed it. Did not fix. only way to have characters rendered is to disable the resource pack with custom bitmap fonts (specifically vanillatweaks with hunger preview utility enabled)

**Comment by purple512** [comment]
I still get boxes with dashloader-1.4.5 and the Vanillatweaks 'SmootherFont' resource pack.

Minecraft 1.16.5 / Java 16.0.1
```
appleskin-fabric-mc1.16.x-2.0.0.jar
dashloader-1.4.5.jar
dynamic-fps-2.0.2.jar
fabric-api-0.36.0+1.16.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.16.5-0.6.6.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.5.jar
minihud-fabric-1.16.4-0.19.0-dev.20201103.184029.jar
modmenu-1.16.9.jar
okzoomer-4.0.1+1.16.2.jar
phosphor-fabric-mc1.16.3-0.7.2+build.12.jar
smoothboot-fabric-1.16.5-1.6.0.jar
sodium-fabric-mc1.16.5-0.2.0+build.4.jar
```

**Comment by alphaqu** [comment]
TTF font support has been added In 2.0
